### ISSUE TITLE
70+ periods in a single line causes an infinite loop in Mime::encodeQuotedPrintable

### ISSUE THREAD

**Issue by usox** [zendframework/zend-mime#33]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-mime/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-mime/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Passing a string, which contains at least of 70 period-characters (but not in the first line), to Mime::encodeQuotedPrintable ends in an infinite loop.

This behaviour was introcued by 2b72be3dcb44176572884bc270a42381519abc05.

### Code to reproduce the issue

```php
$line = "test\n".str_repeat('.', 70);

$result = \Zend\Mime\Mime::encodeQuotedPrintable(
        $line
);

var_dump($result);
```

### Expected results

No infinite loop.

### Actual results

Infinite loop.

**Comment by EugenGanshorn** [comment]
Hi it exists already a preq #32 that fix this behaviour

**Comment by EugenGanshorn** [comment]
Hi, my preq was merged. Can you retry/test this behaviour?

**Comment by usox** [comment]
@EugenGanshorn Fix confirmed. It now works as expected. Thanks!
